---
- name: Install Java
  hosts: all
  become: yes  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Install OpenJDK 8 (Amazon Linux)
      yum:
        name: java
        state: present